# Generated by Django 2.1.2 on 2018-12-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myPageInFomation',
            fields=[
                ('apiprovider', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('userimage', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.CharField(blank=True, max_length=200, null=True)),
                ('joiningdate', models.DateTimeField(null=True)),
                ('votingcount', models.IntegerField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='uploadContents',
            fields=[
                ('IDX', models.IntegerField(primary_key=True, serialize=False)),
                ('writeremail', models.CharField(max_length=50)),
                ('filename', models.CharField(max_length=100)),
                ('contentspath', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('publisheddate', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('tags', models.CharField(max_length=50)),
                ('fileinfo', models.CharField(max_length=250)),
                ('totalpages', models.IntegerField()),
                ('previewpath', models.CharField(max_length=250)),
                ('authorinfo', models.CharField(max_length=1000)),
                ('intro', models.CharField(max_length=1000)),
                ('index', models.CharField(max_length=1000)),
                ('contents', models.CharField(max_length=1000)),
                ('reference', models.CharField(default=True, max_length=1000)),
                ('hash', models.CharField(max_length=150)),
            ],
        ),
    ]
