# Generated by Django 2.1.2 on 2018-12-12 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myPage',
            fields=[
                ('apiprovider', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('name', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('userimage', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.CharField(blank=True, max_length=200, null=True)),
                ('joiningdate', models.DateTimeField(null=True)),
                ('votingcount', models.IntegerField(blank=True, null=True)),
                ('authentication', models.IntegerField(blank=True, null=True)),
                ('uniemail', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
