# Generated by Django 2.1.2 on 2019-01-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='previewInfo',
            fields=[
                ('IDX', models.AutoField(primary_key=True, serialize=False)),
                ('contents_id', models.IntegerField()),
                ('uploadpreviewname', models.CharField(max_length=100)),
                ('ftpsavepreviewname', models.CharField(max_length=100)),
                ('imagepath', models.CharField(max_length=200)),
            ],
        ),
    ]
